### ISSUE TITLE
HookAction trigger order

### ISSUE THREAD

**Issue by skwny** [NestPack/hooks#3]
If multiple HookActions are provided, is it possible to know in what order they will trigger? Experimenting with it makes me think it depends on the order in which they are provided.

E.g:

```
export class ExampleHook {}

@HookAction(ExampleHook)
export class DoubleValueAction1 implements IHookAction {
  async handle(hook: ExampleHook) {
     console.log('in DoubleValueAction1')
  }
}

@HookAction(ExampleHook)
export class DoubleValueAction2 implements IHookAction {
  async handle(hook: ExampleHook) {
     console.log('in DoubleValueAction2')
  }
}

```

With the above implementation, I noticed that the hooks would trigger in the order in which I listed them as providers in the module.

```
// This triggers DoubleValueAction1  then DoubleValueAction2
providers: [
  DoubleValueAction1,
  DoubleValueAction2,
]

// This triggers DoubleValueAction2  then DoubleValueAction1
providers: [
  DoubleValueAction2,
  DoubleValueAction1,
]
```

**Comment by harryhorton** [comment]
@skwny yes, it should be the provided order.

HookActions can be registered from any module in the application, so it didn't make sense to me to try to create any sort of ordering system outside of however your providers work.

Ideally, if you need certain tasks to be completed in order, you should use a single HookAction that performs all the logic in the order that you need. If depending modules aren't related to each other, then the order shouldn't matter. If it does matter, then you'll have another dependency to consider, or, perhaps another connective module should be created. It all depends on how you want to structure your app.

Sorry that I cannot provide a clear rule for this.

Closing this issue for now. Feel free to ask more questions.
